### ISSUE TITLE
Link to the vscode Plugin?

### ISSUE THREAD

**Issue by pegaltier** [tomwhite007/rename-angular-component#14]
**Describe the bug**
Is it possible to have the link to the vscode plugin in the marketplace?

**To Reproduce**

**Expected behavior**

**Screenshots or Demo Repo**
If applicable, add screenshots or link to a repo to help explain your problem.

**Desktop (please complete the following information):**
 - OS: 

**Additional context**

**Comment by tomwhite007** [comment]
Hi Pierre

Yes, here you go: https://marketplace.visualstudio.com/items?itemName=tomwhite007.rename-angular-component

Thanks for pointing that out. I've added the VS Code Marketplace link to the repo About section.

Happy renaming!

Tom
