### ISSUE TITLE
[Feature request] Delete component

### ISSUE THREAD

**Issue by BachiMjavanadze** [tomwhite007/rename-angular-component#36]
Please add `Component delete` feature or create new extension for it. it's very annoying when you mistakenly create component and then began to delete all parts of component and cleaning imports into different modules.

**Comment by tomwhite007** [comment]
Hi @BachiMjavanadze 

Thanks for the stars on Visual Studio Marketplace.

I like your idea here but the effort is non-trivial. If you can get enough votes on this thread, then I'll have a think about getting stuck in. I'd really be looking for at least 10-20 thumbs up for this.

Alternatively, I'd welcome contributions to this repo if you or others want to get involved.

My question for this requested feature is, what would you do in templates where the selector of a component you wanted to delete was? Particullarly if it contained content projection.

Kind regards

Tom

**Comment by tomwhite007** [comment]
Hi @BachiMjavanadze 
This thread has been open a long time and there have been no extra comments.
I believe a partial deletion process would not be particularly useful to a senior developer. Second guessing a sometimes complex task like this is probably a recipe for complaints compared to the rename process which is defined as a set of rules provided by the Angular CLI.
I'm afraid I've decided to close this feature request.
All the best.
