### ISSUE TITLE
Publish extension to https://open-vsx.org/

### ISSUE THREAD

**Issue by smoebody** [tomwhite007/rename-angular-component#39]
Hi

In order to make use of this fine extension with vs-code forks and derivates (such as [openvscode-server](https://github.com/gitpod-io/openvscode-server)) it would help to publish it to open extension-registries such as https://open-vsx.org/

Maybe it is a similar enough process to adapt.

**Comment by tomwhite007** [comment]
Unfortunately, I can't provide support for the open source editions. This extension is very OS file system dependant, and I can't presume it will just work so I won't publish outside the sphere I can test.
