### ISSUE TITLE
Enable Use Over Remote Development

### ISSUE THREAD

**Issue by johnhwright** [tomwhite007/rename-angular-component#40]
**Is your feature request related to a problem? Please describe.**
Not sure what's preventing it, but we do a lot of work over the vscode's remote development and sadly this extension doesn't work.

**Describe the solution you'd like**
Currently just does nothing and prints:
```
------------------------
Rename Angular Component
------------------------
```
to the extension log.

**Describe alternatives you've considered**
Have to remote into the machine hosting the code and run it in a VS code instance locally...

**Additional context**

**Comment by pemibo1986** [comment]
Same for WSL on Windows.

**Comment by tomwhite007** [comment]
Hi guys.

Really appreciate you raising this issue. Unfortunately, it's a no-can-fix.

The underlying process is super filesystem intensive, and on virtual environments, using the VS Code virtual filesystem intensively at scale is super-slow. So, I could do it but you wouldn't be happy waiting 5-10 minutes for it to do its thing.

See [closed issue 28](https://github.com/tomwhite007/rename-angular-component/issues/28)

**Comment by pemibo1986** [comment]
Hi Tom,
thanks for the fast reply. I guess I just use a vs code instance inside of the wsl container only for this awesome extension 😊 .
