### ISSUE TITLE
I don't see the option to rename when Right Clicking the file or folder, and when doing it manually always get an error

### ISSUE THREAD

**Issue by NikolaKrstic94** [tomwhite007/rename-angular-component#41]
**Describe the bug**
I get this error whenever I copy&paste the full path of the file and then continue to the 2nd step of actually renaming the file:

`The component class file must use the same file naming convention as 'dialog-edit-individual-pending-orders.component.desktop.ts' for this process to run.`

**To Reproduce**
F1 in VSCode -> Rename Angular Component -> paste the path of a .ts file that needs renaming -> get the error when trying any rename option, even a single letter change.
**Expected behavior**
It should rename the component.

**Screenshots or Demo Repo**
- ![image](https://user-images.githubusercontent.com/25144458/228279582-fc1deb5e-c79a-43c2-97af-b3616fd62a6b.png)

- ![image](https://user-images.githubusercontent.com/25144458/228279565-bd305ec8-4248-4146-a0e7-9daa4c57b150.png)

- ![image](https://user-images.githubusercontent.com/25144458/228279596-2c41d1e4-d11c-4ecd-9810-7ec170c10a8e.png)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by tomwhite007** [comment]
Hi.
The instructions state that you must enter the file name stub. In your example this should be `dialog-edit-individual-pending-orders`.
This extension is not designed to recieve file paths for any of it's options.
