### ISSUE TITLE
Add option for template renaming, component renaming or file renaming

### ISSUE THREAD

**Issue by ertucode** [tomwhite007/rename-angular-component#42]
Currently, the extension just renames the component, file names and the selector. But I dont use angular file naming conventions so, using this extension is kind of weird for me. While renaming the component it could be nice, If we could just pick options

**Comment by tomwhite007** [comment]
This is a complex process that runs on the proviso you follow a convention. Otherwise it would have to ask a lot more questions to make a custom refactor happen. I'm not prepared to support that level of complexity I'm afraid.
