### ISSUE TITLE
styleUrl to .css file is not renamed

### ISSUE THREAD

**Issue by FANMixco** [tomwhite007/rename-angular-component#45]
**Describe the bug**
When you rename a component, the main CSS is not renamed, especially when you have only one in the section `styleUrl`

**To Reproduce**
Rename any component. The CSS file located in `styleUrl` stays the same.

**Expected behavior**
It should also rename the main CSS file located in `styleUrl`.

**Screenshots or Demo Repo**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 11

**Additional context**

**Comment by FANMixco** [comment]
Amazing plugin by the way! It saved me a lot of headaches! Thank you!

**Comment by tomwhite007** [comment]
Thanks for raising this issue. Interesting this is the first time mentioned, possibly because .css components are a less common choice than .scss.
I've reproduced the bug and I'll start work on a fix for it after the Christmas holidays.

**Comment by tomwhite007** [comment]
Further investigation shows this affects newer applications since the introduction of `styleUrl` over `styleUrls`. This is likely a cause for https://github.com/tomwhite007/rename-angular-component/issues/44. I'm working on a solution now.
