### ISSUE TITLE
Feature doesn’t work when used in WSL under Windows

### ISSUE THREAD

**Issue by mwaibel-go** [tomwhite007/rename-angular-component#46]
**Describe the bug**
The extension fails to find the package.json file when the project is opened in WSL2 on Windows.

**To Reproduce**
1. Open an angular project in VSCode under WSL2 in Windows
2. Right-click on a component in the file explorer
3. Select ‘Rename Angular Component’
4. Enter a new name, press enter

**Expected behavior**
The component should be renamed.

**Desktop (please complete the following information):**
 - OS: Windows 10, Ubuntu in WSL2

**Additional context**

The extension host output reads:

```
2024-01-03 11:20:01.343 [info] ExtensionService#_doActivateExtension tomwhite007.rename-angular-component, startup: false, activationEvent: 'onCommand:rename-angular-component.renameComponent'
2024-01-03 11:20:02.749 [error] Error: ENOENT: no such file or directory, open 'C:\home\mwaibel\projekte\outbound-ccf\outbound-ccf-frontend\package.json'
```

The file you’re looking for is in `/home/mwaibel/projekte/outbound-ccf/outbound-ccf-frontend/package.json`.

**Comment by tomwhite007** [comment]
Hi @mwaibel-go 

My apologies, but I have to mark this Issue as `Won't Fix`, please see: https://github.com/tomwhite007/rename-angular-component/issues/28#issuecomment-1177177664.

WSL only has a virtual file system, so standard Node file system api (which is fast) doesn't work. The virtual file system api is at least 10 times slower given the hammering this extension gives it, which makes this extension unusable in that environment.
