### ISSUE TITLE
Add support for Lazy Loaded route import paths

### ISSUE THREAD

**Issue by tomwhite007** [tomwhite007/rename-angular-component#9]
**Is your feature request related to a problem? Please describe.**
If your rename process renames a folder that contains a lazy loaded module, the router module `Routes` config remains unchanged because the process cannot read it currently. This results in a lazy loaded path import error at build time.

**Describe the solution you'd like**
Add support for the rename process to understand and amend Lazy Loaded route import paths.

**Comment by Dzivo** [comment]
Much needed enhancement. Good extension
